# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cameras',
            new_name='Camera',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
