# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180128_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='lastCaptureFile',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='lastCaptureTime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='result',
            name='jsonresult',
        ),
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
