# Generated by Django 2.1.1 on 2019-04-14 20:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuffs', models.IntegerField(choices=[(1, 'person'), (2, 'bike'), (3, 'car'), (4, 'motorbike'), (5, 'cat'), (6, 'dog'), (7, 'aeroplane'), (8, 'bus'), (9, 'train'), (10, 'truck'), (11, 'boat'), (12, 'bird'), (13, 'backpack'), (14, 'umbrella'), (15, 'chair'), (16, 'sofa'), (17, 'tvmonitor'), (18, 'laptop'), (19, 'mouse'), (20, 'keyboard'), (21, 'book'), (22, 'clock')], default=1)),
                ('actions', models.IntegerField(choices=[(1, 'appear'), (2, 'disappear'), (3, 'present')], default=1)),
                ('sms', models.BooleanField()),
                ('mail', models.BooleanField(default=True)),
                ('call', models.BooleanField()),
                ('alarm', models.BooleanField()),
                ('active', models.BooleanField(default=False)),
                ('mass_alarm', models.BooleanField(default=False)),
                ('when', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('key', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alert_when',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(choices=[('mail', 'mail'), ('sms', 'sms'), ('mass_mail', 'mass_mail'), ('mass_sms', 'mass_sms'), ('mass_call', 'mass_call'), ('call', 'call'), ('alarm', 'alarm'), ('patrol', 'patrol')], max_length=10)),
                ('when', models.DateTimeField(auto_now=True)),
                ('who', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('rec', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('auth_type', models.CharField(choices=[('B', 'Basic'), ('D', 'Digest')], default='B', max_length=1)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('rtsp', models.CharField(blank=True, max_length=200, validators=[django.core.validators.URLValidator(schemes=('rtsp',))])),
                ('stream', models.BooleanField(default=False)),
                ('threshold', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(0.99)])),
                ('gap', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('reso', models.BooleanField(default=False)),
                ('width', models.IntegerField(default=1280)),
                ('height', models.IntegerField(default=720)),
                ('pos_sensivity', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_object', models.CharField(default='', max_length=20)),
                ('result_prob', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('result_loc1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_loc2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_loc3', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_loc4', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alert', models.BooleanField(default='False')),
                ('email_0', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_1', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_2', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_3', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_4', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_5', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_6', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_7', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_8', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('email_9', models.CharField(blank=True, max_length=30, validators=[django.core.validators.EmailValidator])),
                ('phone_number_0', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_1', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_3', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_4', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_5', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_6', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_7', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_8', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number_9', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.ImageField(default='detect', upload_to='camera_images/')),
                ('file2', models.ImageField(default='detect', upload_to='camera_images_box/')),
                ('time', models.DateTimeField(auto_now=True)),
                ('brut', models.TextField(default='')),
                ('alert', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Result'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('stuffs', 'actions')},
        ),
    ]
