# Generated by Django 2.1.1 on 2019-04-23 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_delay', models.DurationField(default=datetime.timedelta(0))),
                ('mail_resent', models.DurationField(default=datetime.timedelta(0, 300))),
                ('mail_post_wait', models.DurationField(default=datetime.timedelta(0, 60))),
                ('sms_delay', models.DurationField(default=datetime.timedelta(0, 30))),
                ('sms_resent', models.DurationField(default=datetime.timedelta(0, 300))),
                ('sms_post_wait', models.DurationField(default=datetime.timedelta(0, 30))),
                ('call_delay', models.DurationField(default=datetime.timedelta(0, 60))),
                ('call_resent', models.DurationField(default=datetime.timedelta(0, 300))),
                ('call_post_wait', models.DurationField(default=datetime.timedelta(0, 30))),
                ('alarm_delay', models.DurationField(default=datetime.timedelta(0))),
                ('alarm_resent', models.DurationField(default=datetime.timedelta(0, 300))),
                ('alarm_post_wait', models.DurationField(default=datetime.timedelta(0, 30))),
            ],
        ),
        migrations.AlterField(
            model_name='alert',
            name='key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert_when',
            name='what',
            field=models.CharField(choices=[('mail', 'mail'), ('sms', 'sms'), ('mass_alarm', 'mass_alarm'), ('call', 'call'), ('alarm', 'alarm'), ('patrol', 'patrol')], max_length=10),
        ),
    ]
