# Generated by Django 2.1.1 on 2019-05-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190503_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='adam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Alert_adam'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='adam_channel',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
    ]
