# Generated by Django 2.1.1 on 2019-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190503_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='adam_channel',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='mass_alarm',
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert_adam',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
    ]
