# Generated by Django 2.1.1 on 2019-05-10 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alert_mass_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, unique=True)),
                ('auth', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('delay', models.DurationField(default=datetime.timedelta(0, 20))),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Alert_hook'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('stuffs', 'actions')},
        ),
    ]
