# Generated by Django 2.1.1 on 2019-05-03 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190503_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_adam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('auth', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('delay', models.DurationField(default=datetime.timedelta(0, 20))),
                ('duration', models.DurationField(default=datetime.timedelta(0, 3600))),
            ],
        ),
        migrations.RemoveField(
            model_name='alert_info',
            name='adam_auth',
        ),
        migrations.RemoveField(
            model_name='alert_info',
            name='adam_delay',
        ),
        migrations.RemoveField(
            model_name='alert_info',
            name='adam_duration',
        ),
        migrations.RemoveField(
            model_name='alert_info',
            name='adam_ip',
        ),
        migrations.RemoveField(
            model_name='alert_info',
            name='adam_pass',
        ),
        migrations.AddField(
            model_name='alert',
            name='adam_channel',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='adam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Alert_adam'),
        ),
    ]
