# Generated by Django 2.1.1 on 2019-05-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20190510_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_hook',
            name='ip',
        ),
        migrations.AddField(
            model_name='alert_hook',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alert_hook',
            name='auth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alert_hook',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
