# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180130_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='result',
        ),
        migrations.AddField(
            model_name='result',
            name='result_loc1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='result',
            name='result_loc2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='result',
            name='result_loc3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='result',
            name='result_object',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='result_prob',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
