# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180206_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_object', models.CharField(default='', max_length=20)),
                ('result_prob', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('result_loc1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_loc2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('result_loc3', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_loc1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_loc2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_loc3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_object',
        ),
        migrations.RemoveField(
            model_name='result',
            name='result_prob',
        ),
        migrations.AddField(
            model_name='object',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Result'),
        ),
    ]
