# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_object_result_loc4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='file',
            new_name='file1',
        ),
        migrations.AddField(
            model_name='result',
            name='file2',
            field=models.ImageField(default=None, upload_to='camera_images_box/'),
            preserve_default=False,
        ),
    ]
