# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180221_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='file',
        ),
        migrations.AddField(
            model_name='result',
            name='file1',
            field=models.ImageField(default='camera_images/detect', upload_to='camera_images/'),
        ),
        migrations.AddField(
            model_name='result',
            name='file2',
            field=models.ImageField(default='camera_images/detect', upload_to='camera_images_box/'),
        ),
    ]
