# Generated by Django 2.1.1 on 2019-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='dataset',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
