# Generated by Django 2.1.1 on 2019-04-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=50)),
                ('size', models.SmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('ratio', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('process', models.SmallIntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.Config')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('config', 'name')},
        ),
    ]
