# Generated by Django 2.0.3 on 2019-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
