# Generated by Django 2.0.3 on 2019-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_image_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
